version: '3.8'
services:
  api:
    build: ./api
    ports:
      - 3333:80
    depends_on:
      - redis
    volumes:
      - "./mount:/mount"
    environment:
      # token to protect the /status endpoint, leave empty to make it public
      - STATUS_TOKEN=
      # token to protect admin features, leave empty to disable them entirely
      - ADMIN_TOKEN=
      # max upload size in bytes
      - MAX_FILE_SIZE=500000000
      # size of uuids for files, increase it to add security or when you're expecting a decent amount of traffic
      - UUID_SIZE=5
      # disable most of logging
      - LOG_LEVEL=critical
      - ACCESS_LOG=
  redis:
    image: "redis:alpine"
    volumes:
    - "./redis_db:/data"