version: '3.8'
services:
  api:
    build: ./api
    ports:
      - 3333:80
    depends_on:
      - redis
    volumes:
      - "./mount:/mount"
#      - "./static:/static"
  redis:
    image: "redis:alpine"
    volumes:
    - "./redis_db:/data"